#alias vi='vim'
alias l='ls -lF'
alias ll='ls -lF'
alias la='ls -lFa'
alias lt='ls -lFrt'
alias h='history'
alias c='clsb'
alias k9='kill -9'

alias m='gmake $MAKE_PARA'
alias md='gmake depend $MAKE_PARA'
alias mi='gmake install $MAKE_PARA'
alias mia='gmake install_all $MAKE_PARA'
alias mih='gmake install_headers $MAKE_PARA'
alias midl='gmake install_idl $MAKE_PARA'
alias mc='gmake clean $MAKE_PARA'
alias mca='gmake clean_all $MAKE_PARA'

alias mf='gmake $MAKE_PARA -f'
alias mdf='gmake $MAKE_PARA depend -f'
alias mif='gmake $MAKE_PARA install -f'
alias miaf='gmake $MAKE_PARA install_all -f'
alias mihf='gmake $MAKE_PARA install_headers -f'
alias mcf='gmake $MAKE_PARA clean -f'
alias mcaf='gmake $MAKE_PARA clean_all -f'

alias sc='source ~/.bashrc'
alias tf='tail -f'
alias psu='ps -u $USER'
alias psga='ps -ef|grep'
alias psg='ps -ef|grep $USER'
alias psgg='ps -ef|grep $USER|grep'
alias ag='alias|grep'
alias eg='env|grep'
alias fn='find . -name '
alias fgh='find . -name "*.h"|xargs grep '
alias fgpy='find . -name "*.py"|xargs grep -nE '
alias fgcpp='find . -name "*.cpp"|xargs grep '
alias fgphp='find . -name "*.php"|xargs grep -nE '
alias fgmak='find . -name "Makefile*"|xargs grep -nE '

